[2024-10-12 17:03:10,664 (/home/ubuntu/FIKA_WCS/db_redis/handle_redis.py:33 - __init__())] INFO -> Connect redis successful
[2024-10-12 17:03:10,735 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:55 - __connect())] INFO -> Successfully connected to PLC at 192.168.31.3:502
[2024-10-12 17:03:10,738 (/home/ubuntu/FIKA_WCS/PLC/plc_controller.py:150 - __check_trigger())] INFO -> START CHECK PLC
[2024-10-12 17:03:10,857 (/home/ubuntu/FIKA_WCS/PLC/plc_controller.py:93 - update_status())] INFO -> Reset error DWS
[2024-10-12 17:03:11,127 (/home/ubuntu/FIKA_WCS/apis/DAL/DAL_server.py:41 - get_token_bearer_backend())] INFO -> Get token seccessful message.
[2024-10-12 17:03:11,152 (/home/ubuntu/FIKA_WCS/agv/agv_manager.py:17 - __init__())] INFO -> START AGV
[2024-10-12 17:03:11,155 (/home/ubuntu/FIKA_WCS/DWS/handle_dws.py:19 - __sub_request())] INFO -> START CHECK DWS
[2024-10-12 17:03:11,157 (/home/ubuntu/FIKA_WCS/markem_printer/printer_manager.py:24 - __sub_print_request())] INFO -> START PRINT MARKEM
[2024-10-12 17:03:11,158 (/home/ubuntu/FIKA_WCS/datamax_printer/printer_manager.py:21 - __sub_print_request())] INFO -> START REPRINT
[2024-10-12 17:03:11,160 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:47 - connect())] INFO -> Connected to 192.168.31.210:9100
[2024-10-12 17:03:11,161 (/home/ubuntu/FIKA_WCS/tranfer/control_tranfer.py:19 - __init__())] INFO -> TRANFER READY
[2024-10-12 17:03:11,162 (/home/ubuntu/FIKA_WCS/tasks/scheduler.py:13 - __run_schedule())] INFO -> SCHEDUAL START
[2024-10-12 17:03:11,169 (/home/ubuntu/FIKA_WCS/apis/__init__.py:39 - start())] INFO -> RestAPI READY
[2024-10-12 17:09:29,606 (/home/ubuntu/FIKA_WCS/db_redis/handle_redis.py:33 - __init__())] INFO -> Connect redis successful
[2024-10-12 17:09:29,675 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:55 - __connect())] INFO -> Successfully connected to PLC at 192.168.31.3:502
[2024-10-12 17:09:29,679 (/home/ubuntu/FIKA_WCS/PLC/plc_controller.py:150 - __check_trigger())] INFO -> START CHECK PLC
[2024-10-12 17:09:29,792 (/home/ubuntu/FIKA_WCS/PLC/plc_controller.py:93 - update_status())] INFO -> Reset error DWS
[2024-10-12 17:09:30,054 (/home/ubuntu/FIKA_WCS/apis/DAL/DAL_server.py:41 - get_token_bearer_backend())] INFO -> Get token seccessful message.
[2024-10-12 17:09:30,078 (/home/ubuntu/FIKA_WCS/agv/agv_manager.py:17 - __init__())] INFO -> START AGV
[2024-10-12 17:09:30,081 (/home/ubuntu/FIKA_WCS/DWS/handle_dws.py:19 - __sub_request())] INFO -> START CHECK DWS
[2024-10-12 17:09:30,084 (/home/ubuntu/FIKA_WCS/markem_printer/printer_manager.py:24 - __sub_print_request())] INFO -> START PRINT MARKEM
[2024-10-12 17:09:30,086 (/home/ubuntu/FIKA_WCS/datamax_printer/printer_manager.py:21 - __sub_print_request())] INFO -> START REPRINT
[2024-10-12 17:09:30,087 (/home/ubuntu/FIKA_WCS/tranfer/control_tranfer.py:19 - __init__())] INFO -> TRANFER READY
[2024-10-12 17:09:30,089 (/home/ubuntu/FIKA_WCS/tasks/scheduler.py:13 - __run_schedule())] INFO -> SCHEDUAL START
[2024-10-12 17:09:30,095 (/home/ubuntu/FIKA_WCS/apis/__init__.py:39 - start())] INFO -> RestAPI READY
[2024-10-12 17:09:33,193 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:50 - connect())] ERROR -> Error connecting to 192.168.31.210:9100 - [Errno 113] No route to host
[2024-10-12 17:09:33,194 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:60 - handle_reconnect())] INFO -> Attempting to reconnect in 1 seconds...
[2024-10-12 17:09:42,281 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:50 - connect())] ERROR -> Error connecting to 192.168.31.210:9100 - [Errno 113] No route to host
[2024-10-12 17:09:42,281 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:60 - handle_reconnect())] INFO -> Attempting to reconnect in 2 seconds...
[2024-10-12 17:09:52,392 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:50 - connect())] ERROR -> Error connecting to 192.168.31.210:9100 - [Errno 113] No route to host
[2024-10-12 17:09:52,393 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:60 - handle_reconnect())] INFO -> Attempting to reconnect in 4 seconds...
[2024-10-12 17:10:04,489 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:50 - connect())] ERROR -> Error connecting to 192.168.31.210:9100 - [Errno 113] No route to host
[2024-10-12 17:10:04,489 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:60 - handle_reconnect())] INFO -> Attempting to reconnect in 8 seconds...
[2024-10-12 17:10:20,552 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:50 - connect())] ERROR -> Error connecting to 192.168.31.210:9100 - [Errno 113] No route to host
[2024-10-12 17:10:20,553 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:60 - handle_reconnect())] INFO -> Attempting to reconnect in 16 seconds...
[2024-10-12 17:10:41,578 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:47 - connect())] INFO -> Connected to 192.168.31.210:9100
[2024-10-12 17:15:18,272 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:103 - read_data())] ERROR -> Error reading from PLC: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.31.3:502)]
[2024-10-12 17:15:19,274 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:15:20,477 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:15:21,860 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:80 - reset_connect())] INFO -> PLC disconnected, closing socket connection...
[2024-10-12 17:15:21,860 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:91 - close())] INFO -> Closed connection to 192.168.31.210:9100
[2024-10-12 17:15:21,879 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:15:23,682 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:15:26,286 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:15:30,492 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:15:37,895 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:15:51,710 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:16:18,338 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:17:10,552 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:18:53,959 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:20:54,964 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:22:56,022 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:24:57,080 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:26:58,175 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:28:59,278 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:31:00,320 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:33:01,422 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:35:02,524 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:37:03,548 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:39:04,651 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:41:05,753 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:43:06,804 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:45:07,816 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:47:08,858 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:49:09,863 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:51:10,965 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:53:12,067 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:55:13,077 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:57:14,180 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 17:59:15,250 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:01:16,352 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:03:17,358 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:05:18,371 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:07:19,474 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:09:20,485 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:11:21,586 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:13:22,646 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:15:23,652 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:17:24,739 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:19:25,841 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:21:26,857 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:23:27,869 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:25:28,971 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:27:30,034 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:29:31,137 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:31:32,210 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:33:33,222 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:35:34,291 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:37:35,371 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:39:36,384 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:41:37,409 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:43:38,414 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:45:39,516 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:47:40,618 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:49:41,633 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:51:42,735 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:53:43,738 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:55:44,766 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:57:45,811 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 18:59:46,821 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:01:47,923 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:03:48,966 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:05:50,066 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:07:51,090 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:09:52,181 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:11:53,283 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:13:54,384 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:15:55,474 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:17:56,576 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:19:57,582 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:21:58,665 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:23:59,766 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:26:00,866 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:28:01,968 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:30:03,009 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:32:04,055 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:34:05,064 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:36:06,067 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:38:07,085 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:40:08,094 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:42:09,097 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:44:10,162 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:46:11,224 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:48:12,258 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:50:13,360 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:52:14,457 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:54:15,550 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:56:16,562 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 19:58:17,619 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:00:18,721 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:02:19,824 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:04:20,858 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:06:21,938 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:08:23,041 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:10:24,073 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:12:25,162 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:14:26,264 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:16:27,271 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:18:28,373 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:20:29,412 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:22:30,447 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:24:31,540 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:26:32,641 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:28:33,742 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:30:34,844 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:32:35,918 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:34:36,946 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:36:38,002 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:38:39,104 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:40:40,206 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:42:41,308 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:44:42,354 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:46:43,456 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:48:44,477 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:50:45,511 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:52:46,613 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:54:47,713 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:56:48,816 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 20:58:49,834 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:00:50,936 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:02:52,038 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:04:53,140 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:06:54,178 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:08:55,227 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:10:56,329 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:12:57,362 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:14:58,464 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:16:59,565 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:19:00,667 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:21:01,721 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:23:02,824 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:25:03,914 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:27:05,015 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:29:06,116 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:31:07,219 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:33:08,320 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:35:09,422 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:37:10,470 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:39:11,540 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:41:12,642 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:43:13,649 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:45:14,751 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:47:15,854 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:49:16,955 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:51:17,989 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:53:19,049 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:55:20,062 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:57:21,104 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 21:59:22,193 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:01:23,215 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:03:24,223 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:05:25,234 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:07:26,316 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:09:27,365 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:11:28,372 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:13:29,475 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:15:30,566 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:17:31,669 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:19:32,700 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:21:33,704 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:23:34,806 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:25:35,823 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:27:36,925 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:29:37,957 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:31:39,042 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:33:40,066 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:35:41,068 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:37:42,131 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:39:43,155 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:41:44,176 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:43:45,191 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:45:46,294 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:47:47,378 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:49:48,449 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:51:49,551 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:53:50,557 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:55:51,660 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:57:52,679 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 22:59:53,765 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:01:54,771 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:03:55,873 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:05:56,975 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:07:57,997 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:09:59,001 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:12:00,050 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:14:01,152 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:16:02,255 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:18:03,325 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:20:04,420 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:22:05,499 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:24:06,601 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:26:07,703 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:28:08,789 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:30:09,891 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:32:10,951 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:34:12,046 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:36:13,093 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:38:14,127 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:40:15,162 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:42:16,264 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:44:17,268 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:46:18,271 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:48:19,285 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:50:20,348 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:52:21,412 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:54:22,416 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:56:23,466 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-12 23:58:24,568 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:00:25,662 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:02:26,669 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:04:27,686 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:06:28,695 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:08:29,797 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:10:30,800 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:12:31,861 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:14:32,963 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:16:33,966 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:18:34,970 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:20:35,978 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:22:37,006 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:24:38,087 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:26:39,115 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:28:40,118 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:30:41,220 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:32:42,223 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:34:43,243 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:36:44,259 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:38:45,269 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:40:46,276 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:42:47,307 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:44:48,399 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:46:49,403 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:48:50,419 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:50:51,433 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:52:52,515 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:54:53,562 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:56:54,664 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 00:58:55,766 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:00:56,784 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:02:57,790 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:04:58,798 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:06:59,803 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:09:00,905 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:11:02,007 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:13:03,047 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:15:04,119 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:17:05,131 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:19:06,135 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:21:07,140 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:23:08,148 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:25:09,161 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:27:10,166 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:29:11,248 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:31:12,351 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:33:13,360 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:35:14,389 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:37:15,490 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:39:16,593 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:41:17,678 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:43:18,773 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:45:19,778 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:47:20,832 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:49:21,841 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:51:22,943 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:53:23,954 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:55:24,962 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:57:26,064 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 01:59:27,154 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:01:28,257 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:03:29,335 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:05:30,347 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:07:31,373 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:09:32,378 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:11:33,397 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:13:34,461 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:15:35,532 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:17:36,610 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:19:37,708 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:21:38,715 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:23:39,810 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:25:40,912 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:27:41,922 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:29:42,965 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:31:43,972 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:33:44,978 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:35:46,080 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:37:47,183 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:39:48,185 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:41:49,250 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:43:50,353 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:45:51,442 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:47:52,456 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:49:53,460 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:51:54,562 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:53:55,576 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:55:56,586 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:57:57,689 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 02:59:58,692 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:01:59,765 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:04:00,772 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:06:01,776 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:08:02,782 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:10:03,790 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:12:04,892 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:14:05,904 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:16:07,003 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:18:08,008 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:20:09,042 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:22:10,145 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:24:11,179 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:26:12,216 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:28:13,285 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:30:14,338 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:32:15,418 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:34:16,520 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:36:17,550 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:38:18,563 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:40:19,567 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:42:20,574 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:44:21,676 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:46:22,682 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:48:23,698 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:50:24,801 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:52:25,807 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:54:26,894 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:56:27,994 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 03:58:29,064 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:00:30,165 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:02:31,174 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:04:32,179 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:06:33,282 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:08:34,289 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:10:35,392 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:12:36,403 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:14:37,411 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:16:38,513 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:18:39,537 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:20:40,569 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:22:41,629 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:24:42,676 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:26:43,765 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:28:44,867 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:30:45,970 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:32:46,975 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:34:47,986 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:36:49,030 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:38:50,039 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:40:51,065 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:42:52,146 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:44:53,249 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:46:54,269 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:48:55,320 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:50:56,372 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:52:57,472 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:54:58,565 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:56:59,597 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 04:59:00,699 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:01:01,704 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:03:02,730 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:05:03,832 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:07:04,875 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:09:05,978 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:11:06,984 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:13:07,994 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:15:09,096 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:17:10,199 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:19:11,282 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:21:12,346 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:23:13,396 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:25:14,485 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:27:15,575 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:29:16,677 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:31:17,780 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:33:18,834 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:35:19,922 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:37:20,935 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:39:22,038 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:41:23,041 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:43:24,048 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:45:25,060 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:47:26,066 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:49:27,169 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:51:28,269 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:53:29,366 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:55:30,372 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:57:31,376 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 05:59:32,382 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:01:33,422 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:03:34,514 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:05:35,607 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:07:36,610 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:09:37,666 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:11:38,670 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:13:39,699 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:15:40,706 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:17:41,808 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:19:42,858 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:21:43,924 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:23:45,026 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:25:46,041 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:27:47,085 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:29:48,188 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:31:49,234 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:33:50,322 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:35:51,336 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:37:52,410 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:39:53,451 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:41:54,546 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:43:55,551 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:45:56,654 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:47:57,682 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:49:58,770 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:51:59,858 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:54:00,879 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:56:01,951 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 06:58:03,053 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:00:04,155 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:02:05,166 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:04:06,211 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:06:07,216 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:08:08,306 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:10:09,394 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:12:10,409 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:14:11,465 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:16:12,567 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:18:13,651 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:20:14,674 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:22:15,736 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:24:16,754 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:26:17,842 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:28:18,930 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:30:19,941 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:32:20,973 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:34:22,066 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:36:23,156 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:38:24,221 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:40:25,323 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:42:26,418 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:44:27,506 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:46:28,609 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:48:29,711 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:50:30,771 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:52:31,858 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:54:32,861 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:56:33,867 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 07:58:34,942 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:00:35,957 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:02:36,965 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:04:37,997 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:06:39,090 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:08:40,171 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:10:41,273 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:12:42,354 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:14:43,432 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:16:44,530 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:18:45,540 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:20:46,642 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:22:47,730 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:24:48,778 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:26:49,834 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:28:50,890 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:30:51,946 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:32:53,020 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:34:54,087 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:36:55,121 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:38:56,167 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:40:57,269 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:42:58,366 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:44:59,371 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:47:00,411 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:49:01,450 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:51:02,546 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:53:03,567 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:55:04,612 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:57:05,675 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 08:59:06,709 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:01:07,786 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:03:08,846 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:05:09,887 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:07:10,954 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:09:12,010 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:11:13,097 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:13:14,199 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:15:15,301 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:17:16,322 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:19:17,354 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:21:18,457 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:23:19,532 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:25:20,635 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:27:21,650 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:29:22,658 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:31:23,690 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:33:24,746 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:35:25,842 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:37:26,944 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:39:28,011 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:41:29,041 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:43:30,053 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:45:31,058 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:47:32,160 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:49:33,230 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:51:34,333 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:53:35,435 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:55:36,493 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:57:37,563 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 09:59:38,638 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:01:39,740 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:03:40,758 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:05:41,859 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:07:42,898 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:09:43,903 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:11:44,988 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:13:46,002 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:15:47,104 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:17:48,135 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:19:49,234 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:21:50,336 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:23:51,438 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:25:52,449 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:27:53,463 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:29:54,528 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:31:55,531 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:33:56,568 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:35:57,581 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:37:58,684 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:39:59,687 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:42:00,690 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:44:01,792 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:46:02,798 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:48:03,900 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:50:05,002 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:52:06,011 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:54:07,019 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:56:08,031 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 10:58:09,034 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:00:10,045 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:02:11,067 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:04:12,073 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:06:13,119 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:08:14,178 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:10:15,251 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:12:16,255 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:14:17,345 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:16:18,372 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:18:19,443 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:20:20,475 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:22:21,553 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:24:22,589 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:26:23,591 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:28:24,694 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:30:25,796 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:32:26,898 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:34:27,998 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:36:29,044 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:38:30,050 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:40:31,062 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:42:32,164 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:44:33,167 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:46:34,188 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:48:35,291 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:50:36,293 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:52:37,396 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:54:38,498 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:56:39,543 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 11:58:40,645 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:00:41,666 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:02:42,669 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:04:43,771 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:06:44,782 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:08:45,884 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:10:46,942 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:12:47,991 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:14:49,015 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:16:50,034 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:18:51,137 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:20:52,210 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:22:53,220 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:24:54,323 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:26:55,425 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:28:56,527 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:30:57,629 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:32:58,636 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:34:59,640 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:37:00,742 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:39:01,843 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:41:02,908 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:43:03,992 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:45:05,016 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:47:06,019 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:49:07,046 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:51:08,128 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:53:09,154 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:55:10,166 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:57:11,261 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 12:59:12,363 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:01:13,465 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:03:14,568 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:05:15,670 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:07:16,673 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:09:17,775 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:11:18,877 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:13:19,924 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:15:21,026 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:17:22,049 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:19:23,140 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:21:24,242 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:23:25,290 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:25:26,393 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:27:27,495 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:29:28,499 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:31:29,551 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:33:30,653 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:35:31,660 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:37:32,672 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:39:33,677 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:41:34,700 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:43:35,802 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:45:36,866 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:47:37,969 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:49:39,058 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:51:40,160 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:53:41,263 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:55:42,271 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:57:43,373 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 13:59:44,463 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:01:45,478 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:03:46,487 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:05:47,530 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:07:48,632 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:09:49,635 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:11:50,704 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:13:51,807 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:15:52,810 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:17:53,912 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:19:55,015 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:21:56,045 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:23:57,048 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:25:58,130 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:27:59,140 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:30:00,168 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:32:01,270 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:34:02,288 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:36:03,390 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:38:04,492 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:40:05,527 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:42:06,565 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:44:07,667 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:46:08,732 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:48:09,747 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:50:10,849 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:52:11,855 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:54:12,862 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:56:13,869 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 14:58:14,972 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:00:16,003 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:02:17,105 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:04:18,121 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:06:19,132 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:08:20,163 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:10:21,265 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:12:22,367 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:14:23,377 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:16:24,479 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:18:25,582 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:20:26,616 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:22:27,626 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:24:28,634 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:26:29,653 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:28:30,755 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:30:31,761 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:32:32,863 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:34:33,873 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:36:34,881 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:38:35,884 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:40:36,978 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:42:37,988 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:44:39,008 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:46:40,011 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:48:41,114 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:50:42,216 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:52:43,314 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:54:44,415 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:56:45,432 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 15:58:46,524 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:00:47,613 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:02:48,649 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:04:49,723 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:06:50,726 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:08:51,826 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:10:52,929 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:12:53,950 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:14:54,957 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:16:56,060 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:18:57,162 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:20:58,166 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:22:59,267 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:25:00,367 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:27:01,467 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:29:02,471 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:31:03,530 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:33:04,582 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:35:05,684 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:37:06,786 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:39:07,860 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:41:08,963 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:43:09,975 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:45:10,982 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:47:11,984 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:49:13,066 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:51:14,137 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:53:15,240 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:55:16,283 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:57:17,306 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 16:59:18,347 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:01:19,412 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:03:20,515 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:05:21,617 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:07:22,719 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:09:23,732 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:11:24,830 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:13:25,832 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:15:26,835 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:17:27,928 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:19:28,945 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:21:30,039 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:23:31,139 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:25:32,146 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:27:33,154 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:29:34,241 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:31:35,333 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:33:36,410 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:35:37,417 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:37:38,506 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:39:39,584 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:41:40,687 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:43:41,714 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:45:42,770 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:47:43,873 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:49:44,966 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:51:45,971 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:53:46,994 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:55:48,020 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:57:49,062 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 17:59:50,109 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:01:51,165 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:03:52,178 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:05:53,266 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:07:54,369 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:09:55,378 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:11:56,382 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:13:57,434 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:15:58,459 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:17:59,531 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:20:00,534 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:22:01,538 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:24:02,552 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:26:03,556 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:28:04,560 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:30:05,663 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:32:06,680 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:34:07,701 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:36:08,754 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:38:09,762 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:40:10,832 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:42:11,889 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:44:12,978 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:46:14,080 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:48:15,091 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:50:16,097 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:52:17,194 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:54:18,250 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:56:19,306 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 18:58:20,369 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:00:21,380 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:02:22,450 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:04:23,536 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:06:24,638 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:08:25,641 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:10:26,698 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:12:27,757 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:14:28,795 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:16:29,866 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:18:30,935 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:20:31,990 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:22:33,034 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:24:34,090 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:26:35,159 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:28:36,262 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:30:37,364 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:32:38,466 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:34:39,533 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:36:40,562 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:38:41,584 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:40:42,588 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:42:43,690 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:44:44,791 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:46:45,794 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:48:46,896 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:50:47,965 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:52:48,987 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:54:50,030 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:56:51,033 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 19:58:52,037 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:00:53,139 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:02:54,149 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:04:55,151 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:06:56,253 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:08:57,356 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:10:58,371 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:12:59,473 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:15:00,515 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:17:01,518 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:19:02,550 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:21:03,642 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:23:04,649 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:25:05,751 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:27:06,853 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:29:07,864 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:31:08,967 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:33:10,069 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:35:11,093 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:37:12,165 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:39:13,211 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:41:14,244 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:43:15,255 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:45:16,358 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:47:17,460 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:49:18,469 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:51:19,540 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:53:20,643 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:55:21,646 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:57:22,679 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 20:59:23,691 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:01:24,792 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:03:25,895 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:05:26,997 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:07:28,003 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:09:29,029 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:11:30,036 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:13:31,091 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:15:32,193 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:17:33,295 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:19:34,306 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:21:35,318 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:23:36,420 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:25:37,468 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:27:38,507 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:29:39,539 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:31:40,641 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:33:41,647 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:35:42,655 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:37:43,678 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:39:44,781 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:41:45,789 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:43:46,892 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:45:47,923 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:47:49,025 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:49:50,065 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:51:51,168 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:53:52,267 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:55:53,270 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:57:54,273 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 21:59:55,283 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:01:56,385 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:03:57,488 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:05:58,590 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:07:59,596 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:10:00,698 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:12:01,715 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:14:02,795 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:16:03,897 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:18:04,967 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:20:06,069 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:22:07,102 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:24:08,105 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:26:09,109 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:28:10,117 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:30:11,220 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:32:12,322 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:34:13,348 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:36:14,450 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:38:15,534 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:40:16,637 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:42:17,718 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:44:18,820 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:46:19,912 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:48:20,950 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:50:22,008 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:52:23,063 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:54:24,070 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:56:25,167 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 22:58:26,269 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:00:27,280 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:02:28,284 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:04:29,386 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:06:30,389 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:08:31,398 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:10:32,501 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:12:33,603 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:14:34,641 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:16:35,698 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:18:36,701 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:20:37,804 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:22:38,906 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:24:40,008 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:26:41,018 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:28:42,120 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:30:43,186 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:32:44,204 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:34:45,300 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:36:46,323 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:38:47,425 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:40:48,490 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:42:49,499 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:44:50,599 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:46:51,612 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:48:52,621 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:50:53,723 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:52:54,776 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:54:55,879 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:56:56,981 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-13 23:58:57,986 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:00:58,996 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:03:00,082 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:05:01,166 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:07:02,217 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:09:03,223 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:11:04,314 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:13:05,354 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:15:06,375 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:17:07,386 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:19:08,401 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:21:09,406 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:23:10,419 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:25:11,521 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:27:12,562 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:29:13,623 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:31:14,662 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:33:15,665 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:35:16,768 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:37:17,870 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:39:18,912 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:41:20,014 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:43:21,023 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:45:22,109 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:47:23,166 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:49:24,186 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:51:25,196 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:53:26,233 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:55:27,315 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:57:28,411 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 00:59:29,495 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:01:30,534 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:03:31,539 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:05:32,641 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:07:33,744 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:09:34,747 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:11:35,790 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:13:36,892 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:15:37,940 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:17:38,952 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:19:40,054 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:21:41,137 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:23:42,146 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:25:43,150 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:27:44,154 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:29:45,166 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:31:46,192 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:33:47,251 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:35:48,347 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:37:49,449 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:39:50,471 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:41:51,538 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:43:52,567 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:45:53,658 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:47:54,666 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:49:55,765 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:51:56,866 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:53:57,931 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:55:58,962 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 01:58:00,064 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:00:01,167 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:02:02,226 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:04:03,283 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:06:04,286 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:08:05,300 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:10:06,316 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:12:07,403 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:14:08,506 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:16:09,593 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:18:10,674 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:20:11,700 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:22:12,786 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:24:13,888 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:26:14,934 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:28:15,957 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:30:17,059 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:32:18,073 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:34:19,133 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:36:20,235 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:38:21,243 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:40:22,298 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:42:23,380 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:44:24,482 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:46:25,579 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:48:26,582 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:50:27,674 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:52:28,776 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:54:29,869 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:56:30,972 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 02:58:32,074 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:00:33,093 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:02:34,138 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:04:35,240 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:06:36,261 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:08:37,283 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:10:38,310 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:12:39,366 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:14:40,455 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:16:41,527 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:18:42,537 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:20:43,639 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:22:44,647 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:24:45,654 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:26:46,691 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:28:47,693 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:30:48,699 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:32:49,732 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:34:50,755 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:36:51,831 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:38:52,933 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:40:53,936 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:42:54,986 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:44:55,996 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:46:57,010 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:48:58,015 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:50:59,060 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:53:00,089 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:55:01,179 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:57:02,184 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 03:59:03,263 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:01:04,276 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:03:05,378 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:05:06,398 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:07:07,444 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:09:08,454 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:11:09,557 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:13:10,659 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:15:11,730 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:17:12,739 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:19:13,841 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:21:14,943 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:23:16,041 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:25:17,143 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:27:18,166 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:29:19,218 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:31:20,256 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:33:21,272 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:35:22,354 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:37:23,442 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:39:24,539 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:41:25,545 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:43:26,578 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:45:27,666 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:47:28,758 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:49:29,764 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:51:30,866 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:53:31,911 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:55:32,982 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:57:33,988 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 04:59:35,090 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:01:36,158 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:03:37,260 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:05:38,295 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:07:39,389 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:09:40,466 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:11:41,554 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:13:42,642 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:15:43,657 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:17:44,698 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:19:45,778 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:21:46,881 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:23:47,983 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:25:48,993 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:27:50,021 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:29:51,090 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:31:52,178 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:33:53,206 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:35:54,211 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:37:55,214 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:39:56,287 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:41:57,362 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:43:58,465 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:45:59,567 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:48:00,661 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:50:01,758 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:52:02,810 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:54:03,815 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:56:04,878 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 05:58:05,881 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:00:06,965 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:02:07,973 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:04:09,074 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:06:10,171 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:08:11,175 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:10:12,181 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:12:13,283 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:14:14,386 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:16:15,488 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:18:16,492 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:20:17,595 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:22:18,626 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:24:19,640 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:26:20,742 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:28:21,761 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:30:22,807 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:32:23,860 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:34:24,936 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:36:25,947 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:38:27,049 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:40:28,151 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:42:29,156 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:44:30,258 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:46:31,261 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:48:32,301 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:50:33,322 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:52:34,425 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:54:35,527 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:56:36,629 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 06:58:37,731 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:00:38,834 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:02:39,931 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:04:40,996 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:06:42,001 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:08:43,104 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:10:44,152 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:12:45,195 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:14:46,297 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:16:47,331 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:18:48,366 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:20:49,462 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:22:50,552 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:24:51,654 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:26:52,732 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:28:53,765 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:30:54,868 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:32:55,932 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:34:57,010 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:36:58,098 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:38:59,128 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:57 - __connect())] ERROR -> Failed to connect to PLC
[2024-10-14 07:40:59,134 (/home/ubuntu/FIKA_WCS/PLC/plc_interface.py:55 - __connect())] INFO -> Successfully connected to PLC at 192.168.31.3:502
[2024-10-14 07:40:59,144 (/home/ubuntu/FIKA_WCS/markem_printer/printer_interface.py:27 - send_data_print_lable())] INFO -> NO DATA PRINT
[2024-10-14 07:41:03,785 (/home/ubuntu/FIKA_WCS/socket_tcp/socket_tcp_interface.py:47 - connect())] INFO -> Connected to 192.168.31.210:9100
[2024-10-14 08:12:08,818 (/home/ubuntu/FIKA_WCS/apis/DAL/DWS_api.py:36 - post())] ERROR -> DWS error connect: Time since last heartbeat is 140308.05 seconds
[2024-10-14 08:20:54,746 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:111 - main())] INFO -> START TASK:MISSION_M4
[2024-10-14 08:25:21,622 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:350 - main())] INFO -> ELEVATOR DOWN READY:255
[2024-10-14 08:25:26,633 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:356 - main())] INFO -> NOTIFY AGV IN ELEVATOR DOWN FOR PLC:255
[2024-10-14 08:26:30,174 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:371 - main())] INFO -> NOTIFY AGV OUT ELEVATOR DOWN FOR PLC:255
[2024-10-14 08:26:57,629 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:419 - main())] INFO -> DONE MISSION:255
[2024-10-14 08:29:20,403 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:111 - main())] INFO -> START TASK:MISSION_M4
[2024-10-14 08:33:16,974 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:350 - main())] INFO -> ELEVATOR DOWN READY:256
[2024-10-14 08:33:21,981 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:356 - main())] INFO -> NOTIFY AGV IN ELEVATOR DOWN FOR PLC:256
[2024-10-14 08:34:25,548 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:371 - main())] INFO -> NOTIFY AGV OUT ELEVATOR DOWN FOR PLC:256
[2024-10-14 08:34:47,907 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:419 - main())] INFO -> DONE MISSION:256
[2024-10-14 09:04:03,052 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:111 - main())] INFO -> START TASK:MISSION_M4
[2024-10-14 09:08:04,785 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:350 - main())] INFO -> ELEVATOR DOWN READY:257
[2024-10-14 09:08:09,796 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:356 - main())] INFO -> NOTIFY AGV IN ELEVATOR DOWN FOR PLC:257
[2024-10-14 09:08:55,545 (/home/ubuntu/FIKA_WCS/PLC/plc_controller.py:93 - update_status())] INFO -> Reset error DWS
[2024-10-14 09:09:09,833 (/home/ubuntu/FIKA_WCS/datamax_printer/printer_manager.py:37 - print())] ERROR -> REPRINT function for datamax error: HTTPConnectionPool(host='192.168.31.205', port=9100): Max retries exceeded with url: /markem/print/show (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x703297db4400>: Failed to establish a new connection: [Errno 113] No route to host'))
[2024-10-14 09:09:13,335 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:371 - main())] INFO -> NOTIFY AGV OUT ELEVATOR DOWN FOR PLC:257
[2024-10-14 09:09:35,692 (/home/ubuntu/FIKA_WCS/agv/agv_mission.py:419 - main())] INFO -> DONE MISSION:257
[2024-10-14 09:13:02,997 (/home/ubuntu/FIKA_WCS/apis/DAL/DWS_api.py:36 - post())] ERROR -> DWS error connect: Time since last heartbeat is 481.99 seconds
[2024-10-14 09:14:08,291 (/home/ubuntu/FIKA_WCS/apis/DAL/DWS_api.py:36 - post())] ERROR -> DWS error connect: Time since last heartbeat is 59.27 seconds
[2024-10-14 09:15:31,129 (/home/ubuntu/FIKA_WCS/apis/DAL/DWS_api.py:36 - post())] ERROR -> DWS error connect: Time since last heartbeat is 82.84 seconds
